from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base


class ChatVerMas(Base):
    """Operational "chat version master" — the current flow (mermaid + main model).

    FIXED external table (structure owned by the operational LangGraph project;
    must never change). Holds the CURRENT flow only; version history lives in the
    PM_FLOW_VER tables. The prompt-management system reads this and (only when the
    main model is editable) updates MAIN_MODEL_NM.
    """

    __tablename__ = "CHAT_VER_MAS"

    # Plain autoincrement PK (not Identity(always)) so demo/test seeds can insert
    # explicit IDs; Oracle defines this as GENERATED BY DEFAULT AS IDENTITY.
    id: Mapped[int] = mapped_column("ID", Integer, primary_key=True, autoincrement=True)
    graph_struct: Mapped[str | None] = mapped_column("GRAPH_STRUCT", Text)
    main_model_nm: Mapped[str | None] = mapped_column("MAIN_MODEL_NM", String(100))
    create_date: Mapped[datetime | None] = mapped_column(
        "CREATE_DATE", DateTime, server_default=func.current_timestamp()
    )
    update_date: Mapped[datetime | None] = mapped_column("UPDATE_DATE", DateTime)
    create_user: Mapped[str | None] = mapped_column("CREATE_USER", String(50))
    update_user: Mapped[str | None] = mapped_column("UPDATE_USER", String(50))
