"""Create + seed the demo CHAT_VER_MAS / NODE_MAS tables in Oracle.

DEMO ONLY. In production these two tables live in the operational (external)
LangGraph project's DB and their **structure must not be changed**. While we are
still on a single local box, this script materializes them in the same Oracle DB
the prompt-management backend uses, with one demo RAG flow, so the UI/flow runs
end-to-end.

- Re-runnable: drops NODE_MAS then CHAT_VER_MAS (FK order) and recreates them.
- Leaves the existing PM_* tables completely untouched.
- Column set matches exactly what the spec fixed:
    CHAT_VER_MAS: ID, GRAPH_STRUCT, MAIN_MODEL_NM (+ standard audit columns)
    NODE_MAS:     ID, CHAT_VER_ID, NODE_NM, MODEL_NM, NODE_DESC, PROMPT,
                  PROMPT_EDIT_ENABLE_YN, MODEL_EDIT_ENABLE_YN,
                  MAIN_MODEL_EDIT_ENABLE_YN, CREATE_DATE, UPDATE_DATE,
                  CREATE_USER, UPDATE_USER

Run:  backend/.venv/Scripts/python.exe backend/scripts/demo_seed_oracle.py
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

import oracledb

# --- DSN resolution: read ORACLE_DSN from backend/.env, else fall back. --------
DEFAULT_DSN = "system/orcl@localhost:1521/orcl"


def read_oracle_dsn() -> str:
    env_path = Path(__file__).resolve().parents[1] / ".env"
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("ORACLE_DSN="):
                return line.split("=", 1)[1].strip()
    return os.environ.get("ORACLE_DSN", DEFAULT_DSN)


def parse_dsn(dsn: str) -> tuple[str, str, str]:
    """'user/password@host:port/SERVICE' -> (user, password, 'host:port/SERVICE')."""
    m = re.match(r"^(?P<user>[^/]+)/(?P<pw>[^@]+)@(?P<target>.+)$", dsn)
    if not m:
        raise SystemExit(f"Cannot parse ORACLE_DSN={dsn!r} (expected user/pw@host:port/SERVICE)")
    return m.group("user"), m.group("pw"), m.group("target")


# --- Demo content -------------------------------------------------------------
GRAPH_STRUCT = """flowchart TD
    start([START]) --> retrieve[Retrieve Context]
    retrieve --> generate[Generate Answer]
    generate --> grade{Grade Answer}
    grade -->|relevant| done([END])
    grade -->|retry| retrieve
"""

MAIN_MODEL_NM = "gemini-2.5-flash"

# MODEL_MAS.GAIA_MODEL_NM — available models for the flow main-model selector.
GAIA_MODELS = ["gemini-2.5-flash", "gemini-2.0-flash", "gpt-4o", "claude-sonnet-4-6"]

GENERATE_PROMPT = (
    "당신은 친절한 AI 도우미입니다. 아래 컨텍스트만 사용하여 사용자의 질문에 "
    "한국어로 정확하게 답변하세요.\n\n"
    "[컨텍스트]\n{{context}}\n\n"
    "[질문]\n{{question}}"
)

GRADE_PROMPT = (
    "다음 답변이 질문에 충분히 답하고 컨텍스트에 근거하는지 평가하세요. "
    '적합하면 "relevant", 부족하면 "retry" 한 단어로만 답하세요.\n\n'
    "[질문]\n{{question}}\n\n"
    "[답변]\n{{answer}}"
)

# NODE_NM == mermaid node id (so the UI can later map a clicked node -> NODE_MAS row).
# (node_id, node_nm, model_nm, node_desc, prompt, prompt_yn, model_yn, main_model_yn)
# MODEL_EDIT_ENABLE_YN is always 'N' (per-node model not editable). The flow main
# model is editable when at least one node has MAIN_MODEL_EDIT_ENABLE_YN='Y'.
NODES = [
    (1, "start", None, "플로우 시작", None, "N", "N", "N"),
    (2, "retrieve", None, "벡터 검색으로 관련 문서 컨텍스트 조회 (RAG)", None, "N", "N", "N"),
    (3, "generate", None, "컨텍스트 기반 답변 생성 (LLM)", GENERATE_PROMPT, "Y", "N", "Y"),
    (4, "grade", None, "생성된 답변의 적합성 평가 (LLM)", GRADE_PROMPT, "Y", "N", "N"),
    (5, "done", None, "플로우 종료", None, "N", "N", "N"),
]

CHAT_VER_ID = 1

DDL_CHAT_VER_MAS = """
CREATE TABLE CHAT_VER_MAS (
    ID            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    GRAPH_STRUCT  CLOB,
    MAIN_MODEL_NM VARCHAR2(100),
    CREATE_DATE   TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_DATE   TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATE_USER   VARCHAR2(50),
    UPDATE_USER   VARCHAR2(50),
    CONSTRAINT PK_CHAT_VER_MAS PRIMARY KEY (ID)
)
"""

DDL_NODE_MAS = """
CREATE TABLE NODE_MAS (
    ID                        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CHAT_VER_ID               NUMBER NOT NULL,
    NODE_NM                   VARCHAR2(200) NOT NULL,
    MODEL_NM                  VARCHAR2(100),
    NODE_DESC                 VARCHAR2(1000),
    PROMPT                    CLOB,
    PROMPT_EDIT_ENABLE_YN     CHAR(1) DEFAULT 'N',
    MODEL_EDIT_ENABLE_YN      CHAR(1) DEFAULT 'N',
    MAIN_MODEL_EDIT_ENABLE_YN CHAR(1) DEFAULT 'N',
    CREATE_DATE               TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_DATE               TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATE_USER               VARCHAR2(50),
    UPDATE_USER               VARCHAR2(50),
    CONSTRAINT PK_NODE_MAS PRIMARY KEY (ID),
    CONSTRAINT FK_NODE_MAS_CHATVER FOREIGN KEY (CHAT_VER_ID)
        REFERENCES CHAT_VER_MAS (ID)
)
"""

DDL_MODEL_MAS = """
CREATE TABLE MODEL_MAS (
    ID            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    GAIA_MODEL_NM VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_MODEL_MAS PRIMARY KEY (ID)
)
"""


def drop_if_exists(cur, table: str) -> None:
    try:
        cur.execute(f"DROP TABLE {table} CASCADE CONSTRAINTS PURGE")
        print(f"  dropped {table}")
    except oracledb.DatabaseError as exc:
        (err,) = exc.args
        if err.code == 942:  # ORA-00942: table or view does not exist
            print(f"  {table} did not exist (skip drop)")
        else:
            raise


def main() -> int:
    user, pw, target = parse_dsn(read_oracle_dsn())
    print(f"Connecting to {target} as {user} ...")
    conn = oracledb.connect(user=user, password=pw, dsn=target)
    cur = conn.cursor()

    print("Dropping demo tables (FK order: NODE_MAS -> CHAT_VER_MAS) ...")
    drop_if_exists(cur, "NODE_MAS")
    drop_if_exists(cur, "CHAT_VER_MAS")
    drop_if_exists(cur, "MODEL_MAS")

    print("Creating tables ...")
    cur.execute(DDL_CHAT_VER_MAS)
    cur.execute(DDL_NODE_MAS)
    cur.execute(DDL_MODEL_MAS)
    cur.executemany(
        "INSERT INTO MODEL_MAS (GAIA_MODEL_NM) VALUES (:1)",
        [(m,) for m in GAIA_MODELS],
    )

    print("Inserting demo data ...")
    cur.setinputsizes(graph=oracledb.DB_TYPE_CLOB)
    cur.execute(
        """
        INSERT INTO CHAT_VER_MAS (ID, GRAPH_STRUCT, MAIN_MODEL_NM, CREATE_USER, UPDATE_USER)
        VALUES (:id, :graph, :model, 'system', 'system')
        """,
        id=CHAT_VER_ID, graph=GRAPH_STRUCT, model=MAIN_MODEL_NM,
    )

    cur.executemany(
        """
        INSERT INTO NODE_MAS
            (ID, CHAT_VER_ID, NODE_NM, MODEL_NM, NODE_DESC, PROMPT,
             PROMPT_EDIT_ENABLE_YN, MODEL_EDIT_ENABLE_YN, MAIN_MODEL_EDIT_ENABLE_YN,
             CREATE_USER, UPDATE_USER)
        VALUES
            (:1, :2, :3, :4, :5, :6, :7, :8, :9, 'system', 'system')
        """,
        [(nid, CHAT_VER_ID, nm, model, desc, prompt, p_yn, m_yn, mm_yn)
         for (nid, nm, model, desc, prompt, p_yn, m_yn, mm_yn) in NODES],
    )
    conn.commit()

    # --- Verify -------------------------------------------------------------
    cur.execute("SELECT COUNT(*) FROM CHAT_VER_MAS")
    n_chat = cur.fetchone()[0]
    cur.execute("SELECT COUNT(*) FROM NODE_MAS")
    n_node = cur.fetchone()[0]
    cur.execute("SELECT COUNT(*) FROM NODE_MAS WHERE PROMPT_EDIT_ENABLE_YN = 'Y'")
    n_llm = cur.fetchone()[0]
    cur.execute("SELECT COUNT(*) FROM MODEL_MAS")
    n_model = cur.fetchone()[0]
    print("\nVerification:")
    print(f"  CHAT_VER_MAS rows           = {n_chat} (expect 1)")
    print(f"  NODE_MAS rows               = {n_node} (expect 5)")
    print(f"  NODE_MAS prompt(LLM) nodes  = {n_llm} (expect 2: generate, grade)")
    print(f"  MODEL_MAS rows              = {n_model} (expect {len(GAIA_MODELS)})")

    cur.execute(
        "SELECT ID, NODE_NM, PROMPT_EDIT_ENABLE_YN, MODEL_NM FROM NODE_MAS ORDER BY ID"
    )
    print("\n  NODE_MAS:")
    for row in cur.fetchall():
        print(f"    #{row[0]} {row[1]:<10} prompt={row[2]} model={row[3]}")

    cur.close()
    conn.close()
    ok = (n_chat == 1 and n_node == 5 and n_llm == 2 and n_model == len(GAIA_MODELS))
    print("\n" + ("DEMO SEED OK" if ok else "DEMO SEED MISMATCH — check output above"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
