-- ============================================================
-- AI Agent Prompt Management System - Initial DDL
-- Target: Oracle 19c+ / XE 21c (also runs on 12c+ with IDENTITY)
-- ============================================================

-- Project
CREATE TABLE PM_PROJECT (
    PROJECT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_NM      VARCHAR2(100) NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    STATUS          VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR2(50) NOT NULL,
    CREATED_DT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_BY      VARCHAR2(50),
    UPDATED_DT      TIMESTAMP
);

-- Node
CREATE TABLE PM_NODE (
    NODE_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_ID      NUMBER NOT NULL REFERENCES PM_PROJECT(PROJECT_ID),
    NODE_KEY        VARCHAR2(100) NOT NULL,
    NODE_NM         VARCHAR2(200) NOT NULL,
    NODE_TYPE       VARCHAR2(50),
    POS_X           NUMBER,
    POS_Y           NUMBER,
    DESCRIPTION     VARCHAR2(1000),
    CREATED_BY      VARCHAR2(50) NOT NULL,
    CREATED_DT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UQ_PM_NODE_KEY UNIQUE (PROJECT_ID, NODE_KEY)
);

-- Edge
CREATE TABLE PM_NODE_EDGE (
    EDGE_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROJECT_ID      NUMBER NOT NULL REFERENCES PM_PROJECT(PROJECT_ID),
    SOURCE_NODE_ID  NUMBER NOT NULL REFERENCES PM_NODE(NODE_ID),
    TARGET_NODE_ID  NUMBER NOT NULL REFERENCES PM_NODE(NODE_ID),
    LABEL           VARCHAR2(100),
    CONDITION_EXPR  VARCHAR2(500)
);

-- Model config (versioned)
CREATE TABLE PM_MODEL_CONFIG (
    CONFIG_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NODE_ID         NUMBER NOT NULL REFERENCES PM_NODE(NODE_ID),
    VERSION_NO      VARCHAR2(20) NOT NULL,
    MODEL_PROVIDER  VARCHAR2(50) NOT NULL,
    MODEL_NM        VARCHAR2(100) NOT NULL,
    TEMPERATURE     NUMBER(3,2) DEFAULT 0.7,
    MAX_TOKENS      NUMBER DEFAULT 2048,
    TOP_P           NUMBER(3,2),
    EXTRA_PARAMS    CLOB,
    IS_ACTIVE       CHAR(1) DEFAULT 'N',
    CHANGE_REASON   VARCHAR2(500),
    CREATED_BY      VARCHAR2(50) NOT NULL,
    CREATED_DT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UQ_PM_MODEL_CONFIG UNIQUE (NODE_ID, VERSION_NO)
);

-- Prompt version
CREATE TABLE PM_PROMPT_VERSION (
    PROMPT_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NODE_ID         NUMBER NOT NULL REFERENCES PM_NODE(NODE_ID),
    CONFIG_ID       NUMBER REFERENCES PM_MODEL_CONFIG(CONFIG_ID),
    VERSION_NO      VARCHAR2(20) NOT NULL,
    SYSTEM_PROMPT   CLOB,
    USER_PROMPT     CLOB,
    IS_ACTIVE       CHAR(1) DEFAULT 'N',
    CHANGE_SUMMARY  VARCHAR2(500),
    CHANGE_REASON   VARCHAR2(1000),
    PREV_PROMPT_ID  NUMBER REFERENCES PM_PROMPT_VERSION(PROMPT_ID),
    CREATED_BY      VARCHAR2(50) NOT NULL,
    CREATED_DT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UQ_PM_PROMPT_VERSION UNIQUE (NODE_ID, VERSION_NO)
);

-- Prompt variable
CREATE TABLE PM_PROMPT_VARIABLE (
    VAR_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROMPT_ID       NUMBER NOT NULL REFERENCES PM_PROMPT_VERSION(PROMPT_ID),
    VAR_NAME        VARCHAR2(100) NOT NULL,
    VAR_TYPE        VARCHAR2(50) DEFAULT 'STRING',
    DESCRIPTION     VARCHAR2(300),
    DEFAULT_VALUE   VARCHAR2(500),
    IS_REQUIRED     CHAR(1) DEFAULT 'Y'
);

-- Test dataset
CREATE TABLE PM_TEST_DATASET (
    DATASET_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NODE_ID         NUMBER NOT NULL REFERENCES PM_NODE(NODE_ID),
    DATASET_NM      VARCHAR2(200) NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    IS_ACTIVE       CHAR(1) DEFAULT 'Y',
    CREATED_BY      VARCHAR2(50) NOT NULL,
    CREATED_DT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE PM_TEST_CASE (
    CASE_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATASET_ID      NUMBER NOT NULL REFERENCES PM_TEST_DATASET(DATASET_ID),
    INPUT_DATA      CLOB NOT NULL,
    EXPECTED_OUTPUT CLOB,
    EVAL_CRITERIA   CLOB,
    CASE_TYPE       VARCHAR2(50) DEFAULT 'NORMAL',
    CREATED_BY      VARCHAR2(50) NOT NULL,
    CREATED_DT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Test run
CREATE TABLE PM_TEST_RUN (
    RUN_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RUN_TYPE        VARCHAR2(20) NOT NULL,
    NODE_ID         NUMBER REFERENCES PM_NODE(NODE_ID),
    PROJECT_ID      NUMBER REFERENCES PM_PROJECT(PROJECT_ID),
    PROMPT_ID       NUMBER REFERENCES PM_PROMPT_VERSION(PROMPT_ID),
    DATASET_ID      NUMBER REFERENCES PM_TEST_DATASET(DATASET_ID),
    STATUS          VARCHAR2(20) DEFAULT 'PENDING',
    TOTAL_CASES     NUMBER DEFAULT 0,
    PASSED_CASES    NUMBER DEFAULT 0,
    FAILED_CASES    NUMBER DEFAULT 0,
    AVG_LATENCY_MS  NUMBER,
    TOTAL_TOKENS    NUMBER,
    STARTED_DT      TIMESTAMP,
    ENDED_DT        TIMESTAMP,
    CREATED_BY      VARCHAR2(50) NOT NULL,
    CREATED_DT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Test result per case
CREATE TABLE PM_TEST_RESULT (
    RESULT_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RUN_ID          NUMBER NOT NULL REFERENCES PM_TEST_RUN(RUN_ID),
    CASE_ID         NUMBER REFERENCES PM_TEST_CASE(CASE_ID),
    ACTUAL_OUTPUT   CLOB,
    IS_PASSED       CHAR(1),
    EVAL_DETAIL     CLOB,
    LATENCY_MS      NUMBER,
    INPUT_TOKENS    NUMBER,
    OUTPUT_TOKENS   NUMBER,
    ERROR_MSG       VARCHAR2(1000),
    EXECUTED_DT     TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- RAGAS run
CREATE TABLE PM_RAGAS_RUN (
    RAGAS_RUN_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NODE_ID         NUMBER NOT NULL REFERENCES PM_NODE(NODE_ID),
    PROMPT_ID       NUMBER NOT NULL REFERENCES PM_PROMPT_VERSION(PROMPT_ID),
    DATASET_ID      NUMBER NOT NULL REFERENCES PM_TEST_DATASET(DATASET_ID),
    STATUS          VARCHAR2(20) DEFAULT 'PENDING',
    FAITHFULNESS    NUMBER(5,4),
    ANSWER_RELEVANCY NUMBER(5,4),
    CONTEXT_PRECISION NUMBER(5,4),
    CONTEXT_RECALL  NUMBER(5,4),
    ANSWER_CORRECTNESS NUMBER(5,4),
    STARTED_DT      TIMESTAMP,
    ENDED_DT        TIMESTAMP,
    CREATED_BY      VARCHAR2(50) NOT NULL,
    CREATED_DT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Audit log
CREATE TABLE PM_AUDIT_LOG (
    LOG_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TARGET_TABLE    VARCHAR2(50) NOT NULL,
    TARGET_ID       NUMBER NOT NULL,
    ACTION          VARCHAR2(20) NOT NULL,
    BEFORE_VALUE    CLOB,
    AFTER_VALUE     CLOB,
    CREATED_BY      VARCHAR2(50) NOT NULL,
    CREATED_DT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_PM_NODE_PROJECT ON PM_NODE(PROJECT_ID);
CREATE INDEX IDX_PM_EDGE_PROJECT ON PM_NODE_EDGE(PROJECT_ID);
CREATE INDEX IDX_PM_PROMPT_NODE ON PM_PROMPT_VERSION(NODE_ID);
CREATE INDEX IDX_PM_PROMPT_ACTIVE ON PM_PROMPT_VERSION(NODE_ID, IS_ACTIVE);
CREATE INDEX IDX_PM_MODEL_NODE ON PM_MODEL_CONFIG(NODE_ID);
CREATE INDEX IDX_PM_MODEL_ACTIVE ON PM_MODEL_CONFIG(NODE_ID, IS_ACTIVE);
CREATE INDEX IDX_PM_AUDIT_TARGET ON PM_AUDIT_LOG(TARGET_TABLE, TARGET_ID);
CREATE INDEX IDX_PM_AUDIT_DT ON PM_AUDIT_LOG(CREATED_DT);
