-- ============================================================
-- AutoPrompt (PM) — PM-owned schema DDL  (Oracle 19c+ / XE 21c, 12c+ IDENTITY)
--
-- Authoritative source = the app's DB layer (src/lib/db/rows.ts + services).
-- PM is fully self-contained: node identity is NODE_NM and there are NO FKs to
-- external operational tables (CHAT_VER_MAS / NODE_MAS / MODEL_MAS). RAGAS is
-- flow-scoped only. Apply these 6 tables to the PM Oracle schema (config.yml db).
-- ============================================================

-- 1) Node prompt version history. The agent reads the active row (IS_ACTIVE='Y').
CREATE TABLE PM_NODE_PROMPT_VER (
    PROMPT_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NODE_NM         VARCHAR2(200) NOT NULL,
    VERSION_NO      VARCHAR2(20) NOT NULL,
    SYSTEM_PROMPT   CLOB,
    USER_PROMPT     CLOB,
    MODEL_NM        VARCHAR2(100),
    IS_ACTIVE       VARCHAR2(1) DEFAULT 'N',
    CHANGE_SUMMARY  VARCHAR2(500),
    CHANGE_REASON   VARCHAR2(1000),
    PREV_PROMPT_ID  NUMBER REFERENCES PM_NODE_PROMPT_VER(PROMPT_ID),
    CREATED_BY      VARCHAR2(50) NOT NULL,
    CREATED_DT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_DT      TIMESTAMP,
    CONSTRAINT UQ_PM_NODE_PROMPT_VER UNIQUE (NODE_NM, VERSION_NO)
);

-- 2) Test dataset (RAGAS golden set). IS_ACTIVE='N' hides internal datasets
--    (e.g. the direct-call sink) from the user-facing list.
CREATE TABLE PM_TEST_DATASET (
    DATASET_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATASET_NM      VARCHAR2(200) NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    IS_ACTIVE       VARCHAR2(1) DEFAULT 'Y',
    CREATED_BY      VARCHAR2(50) NOT NULL,
    CREATED_DT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 3) Test case (one golden Q/A; INPUT_DATA is JSON: question/contexts/ground_truth).
CREATE TABLE PM_TEST_CASE (
    CASE_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATASET_ID      NUMBER NOT NULL REFERENCES PM_TEST_DATASET(DATASET_ID),
    INPUT_DATA      CLOB NOT NULL,
    EXPECTED_OUTPUT CLOB,
    EVAL_CRITERIA   CLOB,
    CASE_TYPE       VARCHAR2(50) DEFAULT 'NORMAL',
    CREATED_BY      VARCHAR2(50) NOT NULL,
    CREATED_DT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 4) RAGAS run (flow-scoped aggregate). PROMPT_ID records the node version under
--    test (A/B); AB_GROUP_ID links the two runs of one comparison. ENGINE='direct'
--    marks a raw external-API call (no scoring).
CREATE TABLE PM_RAGAS_RUN (
    RAGAS_RUN_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROMPT_ID          NUMBER REFERENCES PM_NODE_PROMPT_VER(PROMPT_ID),
    AB_GROUP_ID        NUMBER,
    DATASET_ID         NUMBER NOT NULL REFERENCES PM_TEST_DATASET(DATASET_ID),
    STATUS             VARCHAR2(20) DEFAULT 'PENDING',
    FAITHFULNESS       NUMBER(5,4),
    ANSWER_RELEVANCY   NUMBER(5,4),
    CONTEXT_PRECISION  NUMBER(5,4),
    CONTEXT_RECALL     NUMBER(5,4),
    ANSWER_CORRECTNESS NUMBER(5,4),
    JUDGE_PROVIDER     VARCHAR2(50),
    JUDGE_MODEL        VARCHAR2(100),
    METRICS            CLOB,
    ENGINE             VARCHAR2(20),
    ERROR_MSG          CLOB,
    STARTED_DT         TIMESTAMP,
    ENDED_DT           TIMESTAMP,
    CREATED_BY         VARCHAR2(50) NOT NULL,
    CREATED_DT         TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 5) RAGAS per-case result.
CREATE TABLE PM_RAGAS_RESULT (
    RAGAS_RESULT_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RAGAS_RUN_ID       NUMBER NOT NULL REFERENCES PM_RAGAS_RUN(RAGAS_RUN_ID),
    CASE_ID            NUMBER REFERENCES PM_TEST_CASE(CASE_ID),
    QUESTION           CLOB,
    ANSWER             CLOB,
    CONTEXTS           CLOB,
    GROUND_TRUTH       CLOB,
    FAITHFULNESS       NUMBER(5,4),
    ANSWER_RELEVANCY   NUMBER(5,4),
    CONTEXT_PRECISION  NUMBER(5,4),
    CONTEXT_RECALL     NUMBER(5,4),
    ANSWER_CORRECTNESS NUMBER(5,4),
    ERROR_MSG          CLOB,
    CREATED_DT         TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 6) Audit log (prompt/dataset create/edit/delete history).
CREATE TABLE PM_AUDIT_LOG (
    LOG_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TARGET_TABLE    VARCHAR2(50) NOT NULL,
    TARGET_ID       NUMBER NOT NULL,
    ACTION          VARCHAR2(20) NOT NULL,
    BEFORE_VALUE    CLOB,
    AFTER_VALUE     CLOB,
    CREATED_BY      VARCHAR2(50) NOT NULL,
    CREATED_DT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_PM_PROMPT_NODENM_ACT ON PM_NODE_PROMPT_VER (NODE_NM, IS_ACTIVE);
CREATE INDEX IDX_PM_RAGASRESULT_RUN   ON PM_RAGAS_RESULT (RAGAS_RUN_ID);
CREATE INDEX IDX_PM_RAGASRUN_DATASET  ON PM_RAGAS_RUN (DATASET_ID);
CREATE INDEX IDX_PM_AUDIT_TARGET      ON PM_AUDIT_LOG (TARGET_TABLE, TARGET_ID);
