-- ============================================================
-- PM_* → PTX_* 이름 변경 마이그레이션 (기존 DB 가 있을 때만 실행)
--
-- 새로 만드는 스키마라면 이 파일 대신 ddl_initial.sql 을 쓴다.
-- PTX 스키마 소유 계정으로 접속해서 위에서부터 순서대로 실행할 것.
-- 데이터는 그대로 보존된다(테이블/컬럼 이름과 제약만 바뀐다).
-- ============================================================

-- 1) 테이블 이름 -------------------------------------------------------------
RENAME PM_NODE_PROMPT_VER TO PTX_PROMPT_HIS;
RENAME PM_TEST_DATASET    TO PTX_DATASET_MAS;
RENAME PM_TEST_CASE       TO PTX_DATASET_DET;
RENAME PM_RAGAS_RUN       TO PTX_RUN_MAS;
RENAME PM_RAGAS_RESULT    TO PTX_RUN_DET;
RENAME PM_AUDIT_LOG       TO PTX_AUDIT_HIS;

-- 2) 컬럼 이름 ---------------------------------------------------------------
ALTER TABLE PTX_PROMPT_HIS RENAME COLUMN SYSTEM_PROMPT  TO SYSTEM_CTN;
ALTER TABLE PTX_PROMPT_HIS RENAME COLUMN USER_PROMPT    TO USER_CTN;
ALTER TABLE PTX_PROMPT_HIS RENAME COLUMN IS_ACTIVE      TO ACTIVE_YN;
ALTER TABLE PTX_PROMPT_HIS RENAME COLUMN CHANGE_SUMMARY TO SUMMARY_CTN;
ALTER TABLE PTX_PROMPT_HIS RENAME COLUMN CHANGE_REASON  TO REASON_CTN;
ALTER TABLE PTX_PROMPT_HIS RENAME COLUMN CREATED_BY     TO USER_ID;
ALTER TABLE PTX_PROMPT_HIS RENAME COLUMN CREATED_DT     TO CRT_TM;
ALTER TABLE PTX_PROMPT_HIS RENAME COLUMN UPDATED_DT     TO UPDATE_TM;

ALTER TABLE PTX_DATASET_MAS RENAME COLUMN DESCRIPTION TO DESC_CTN;
ALTER TABLE PTX_DATASET_MAS RENAME COLUMN IS_ACTIVE   TO ACTIVE_YN;
ALTER TABLE PTX_DATASET_MAS RENAME COLUMN CREATED_BY  TO USER_ID;
ALTER TABLE PTX_DATASET_MAS RENAME COLUMN CREATED_DT  TO CRT_TM;

ALTER TABLE PTX_DATASET_DET RENAME COLUMN INPUT_DATA      TO INPUT_CTN;
ALTER TABLE PTX_DATASET_DET RENAME COLUMN EXPECTED_OUTPUT TO EXPECT_CTN;
ALTER TABLE PTX_DATASET_DET RENAME COLUMN EVAL_CRITERIA   TO CRITERIA_CTN;
ALTER TABLE PTX_DATASET_DET RENAME COLUMN CASE_TYPE       TO TYPE_CD;
ALTER TABLE PTX_DATASET_DET RENAME COLUMN CREATED_BY      TO USER_ID;
ALTER TABLE PTX_DATASET_DET RENAME COLUMN CREATED_DT      TO CRT_TM;

ALTER TABLE PTX_RUN_MAS RENAME COLUMN RAGAS_RUN_ID       TO RUN_ID;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN STATUS             TO STATUS_CD;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN ENGINE             TO ENGINE_CD;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN METRICS            TO METRIC_CTN;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN JUDGE_PROVIDER     TO JUDGE_PROVIDER_CD;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN JUDGE_MODEL        TO JUDGE_MODEL_NM;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN ERROR_MSG          TO ERROR_CTN;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN STARTED_DT         TO START_TM;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN ENDED_DT           TO END_TM;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN CREATED_BY         TO USER_ID;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN CREATED_DT         TO CRT_TM;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN EXACT_MATCH        TO EXACT_VAL;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN FAITHFULNESS       TO FAITH_VAL;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN ANSWER_RELEVANCY   TO ANS_RELEVANCY_VAL;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN CONTEXT_PRECISION  TO CNTX_PRECISION_VAL;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN CONTEXT_RECALL     TO CNTX_RECALL_VAL;
ALTER TABLE PTX_RUN_MAS RENAME COLUMN ANSWER_CORRECTNESS TO ANS_CORRECTNESS_VAL;

ALTER TABLE PTX_RUN_DET RENAME COLUMN RAGAS_RESULT_ID    TO RESULT_ID;
ALTER TABLE PTX_RUN_DET RENAME COLUMN RAGAS_RUN_ID       TO RUN_ID;
ALTER TABLE PTX_RUN_DET RENAME COLUMN QUESTION           TO QUESTION_CTN;
ALTER TABLE PTX_RUN_DET RENAME COLUMN ANSWER             TO ANSWER_CTN;
ALTER TABLE PTX_RUN_DET RENAME COLUMN CONTEXTS           TO CONTEXT_CTN;
ALTER TABLE PTX_RUN_DET RENAME COLUMN GROUND_TRUTH       TO TRUTH_CTN;
ALTER TABLE PTX_RUN_DET RENAME COLUMN ERROR_MSG          TO ERROR_CTN;
ALTER TABLE PTX_RUN_DET RENAME COLUMN CREATED_DT         TO CRT_TM;
ALTER TABLE PTX_RUN_DET RENAME COLUMN EXACT_MATCH        TO EXACT_VAL;
ALTER TABLE PTX_RUN_DET RENAME COLUMN FAITHFULNESS       TO FAITH_VAL;
ALTER TABLE PTX_RUN_DET RENAME COLUMN ANSWER_RELEVANCY   TO ANS_RELEVANCY_VAL;
ALTER TABLE PTX_RUN_DET RENAME COLUMN CONTEXT_PRECISION  TO CNTX_PRECISION_VAL;
ALTER TABLE PTX_RUN_DET RENAME COLUMN CONTEXT_RECALL     TO CNTX_RECALL_VAL;
ALTER TABLE PTX_RUN_DET RENAME COLUMN ANSWER_CORRECTNESS TO ANS_CORRECTNESS_VAL;

ALTER TABLE PTX_AUDIT_HIS RENAME COLUMN TARGET_TABLE TO TARGET_TABLE_NM;
ALTER TABLE PTX_AUDIT_HIS RENAME COLUMN ACTION       TO ACTION_CD;
ALTER TABLE PTX_AUDIT_HIS RENAME COLUMN BEFORE_VALUE TO BEFORE_CTN;
ALTER TABLE PTX_AUDIT_HIS RENAME COLUMN AFTER_VALUE  TO AFTER_CTN;
ALTER TABLE PTX_AUDIT_HIS RENAME COLUMN CREATED_BY   TO USER_ID;
ALTER TABLE PTX_AUDIT_HIS RENAME COLUMN CREATED_DT   TO CRT_TM;

-- 3) 실행 기록이 데이터셋 삭제와 무관해지도록 ---------------------------------
--    DATASET_NM 은 실행 시점 이름 스냅샷, DATASET_ID 는 NULL 허용으로 바꾼다.
ALTER TABLE PTX_RUN_MAS ADD (DATASET_NM VARCHAR2(200));
UPDATE PTX_RUN_MAS r
   SET DATASET_NM = (SELECT d.DATASET_NM FROM PTX_DATASET_MAS d WHERE d.DATASET_ID = r.DATASET_ID)
 WHERE DATASET_NM IS NULL;
ALTER TABLE PTX_RUN_MAS MODIFY (DATASET_ID NULL);
COMMIT;

-- 4) FK 재정의 — 삭제 규칙을 제약에 박는다 -----------------------------------
--    기존 FK 는 이름이 시스템 생성(SYS_C…)일 수 있어 조회해서 전부 떨군다.
BEGIN
  FOR c IN (SELECT table_name, constraint_name
              FROM user_constraints
             WHERE constraint_type = 'R'
               AND table_name IN ('PTX_PROMPT_HIS','PTX_DATASET_DET','PTX_RUN_MAS','PTX_RUN_DET'))
  LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE '||c.table_name||' DROP CONSTRAINT '||c.constraint_name;
  END LOOP;
END;
/

ALTER TABLE PTX_PROMPT_HIS ADD CONSTRAINT FK_PTX_PROMPT_PREV
  FOREIGN KEY (PREV_PROMPT_ID) REFERENCES PTX_PROMPT_HIS(PROMPT_ID) ON DELETE SET NULL;

ALTER TABLE PTX_DATASET_DET ADD CONSTRAINT FK_PTX_DATASET_DET_MAS
  FOREIGN KEY (DATASET_ID) REFERENCES PTX_DATASET_MAS(DATASET_ID) ON DELETE CASCADE;

ALTER TABLE PTX_RUN_MAS ADD CONSTRAINT FK_PTX_RUN_MAS_PROMPT
  FOREIGN KEY (PROMPT_ID) REFERENCES PTX_PROMPT_HIS(PROMPT_ID) ON DELETE SET NULL;

ALTER TABLE PTX_RUN_MAS ADD CONSTRAINT FK_PTX_RUN_MAS_DATASET
  FOREIGN KEY (DATASET_ID) REFERENCES PTX_DATASET_MAS(DATASET_ID) ON DELETE SET NULL;

ALTER TABLE PTX_RUN_DET ADD CONSTRAINT FK_PTX_RUN_DET_MAS
  FOREIGN KEY (RUN_ID) REFERENCES PTX_RUN_MAS(RUN_ID) ON DELETE CASCADE;

ALTER TABLE PTX_RUN_DET ADD CONSTRAINT FK_PTX_RUN_DET_CASE
  FOREIGN KEY (CASE_ID) REFERENCES PTX_DATASET_DET(CASE_ID) ON DELETE SET NULL;

-- 5) 제약/인덱스 이름 --------------------------------------------------------
ALTER TABLE PTX_PROMPT_HIS RENAME CONSTRAINT UQ_PM_NODE_PROMPT_VER TO UQ_PTX_PROMPT_HIS;

ALTER INDEX IDX_PM_PROMPT_NODENM_ACT RENAME TO IDX_PTX_PROMPT_NODE;
ALTER INDEX IDX_PM_RAGASRESULT_RUN   RENAME TO IDX_PTX_RUN_DET_RUN;
ALTER INDEX IDX_PM_RAGASRUN_DATASET  RENAME TO IDX_PTX_RUN_MAS_DS;
ALTER INDEX IDX_PM_AUDIT_TARGET      RENAME TO IDX_PTX_AUDIT_TARGET;

-- 6) 감사 로그에 남아 있는 옛 테이블 이름 ------------------------------------
UPDATE PTX_AUDIT_HIS
   SET TARGET_TABLE_NM = CASE TARGET_TABLE_NM
         WHEN 'PM_NODE_PROMPT_VER' THEN 'PTX_PROMPT_HIS'
         WHEN 'PM_TEST_DATASET'    THEN 'PTX_DATASET_MAS'
         WHEN 'PM_TEST_CASE'       THEN 'PTX_DATASET_DET'
         WHEN 'PM_RAGAS_RUN'       THEN 'PTX_RUN_MAS'
         WHEN 'PM_RAGAS_RESULT'    THEN 'PTX_RUN_DET'
         WHEN 'PM_AUDIT_LOG'       THEN 'PTX_AUDIT_HIS'
         ELSE TARGET_TABLE_NM
       END
 WHERE TARGET_TABLE_NM LIKE 'PM\_%' ESCAPE '\';
COMMIT;
